spring.application.name=finance-bff-web
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.secure-port-enabled=true
eureka.instance.non-secure-port-enabled=false
server.port=8081
server.ssl.key-store=classpath:finance-keystore.p12
server.ssl.key-store-password=fec4a5n5
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=finance-local
server.ssl.enabled=true
# Configuración OAuth2 con GitHub
server.forward-headers-strategy=framework
spring.security.oauth2.client.registration.github-web.provider=github
spring.security.oauth2.client.registration.github-web.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github-web.client-secret=${GITHUB_CLIENT_SECRET}
# --- CONFIGURACIÓN DE RESILIENCE4J ---
resilience4j.circuitbreaker.instances.financeCore.sliding-window-size=5
resilience4j.circuitbreaker.instances.financeCore.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.financeCore.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.financeCore.permitted-number-of-calls-in-half-open-state=3

spring.kafka.bootstrap-servers=finance-kafka:9092